config/routes.rb
Rails.application.routes.draw do
  resources :projetos
  root   "projetos#index"
  resources :tasks
  resources :histories
  devise_for :users
  get "person" => "person#index"
  get '/next/:id', to: 'histories#nextStatus', as: 'nextHistory'
  get '/back/:id', to: 'histories#backStatus', as: 'backHistory'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/projeto.rb
class Projeto < ApplicationRecord
  belongs_to :user
  has_many :history
end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  before_action :set_projeto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projetos
  # GET /projetos.json
  def index
    @projetos = Projeto.all
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
  end

  # GET /projetos/new
  def new
    @projeto = Projeto.new
    @users = User.all
  end

  # GET /projetos/1/edit
  def edit
    c
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = Projeto.new(projeto_params)

    respond_to do |format|
      if @projeto.save
        format.html { redirect_to @projeto, notice: 'Projeto was successfully created.' }
        format.json { render :show, status: :created, location: @projeto }
      else
        format.html { render :new }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projetos/1
  # PATCH/PUT /projetos/1.json
  def update
    respond_to do |format|
      if @projeto.update(projeto_params)
        format.html { redirect_to @projeto, notice: 'Projeto was successfully updated.' }
        format.json { render :show, status: :ok, location: @projeto }
      else
        format.html { render :edit }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto.destroy
    respond_to do |format|
      format.html { redirect_to projetos_url, notice: 'Projeto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_params
      params.require(:projeto).permit(:name, :user_id)
    end
end

app/helpers/projetos_helper.rb
module ProjetosHelper
end

app/views/projetos/_form.html.erb
<%= form_for @projeto, :html => { :class => "form-horizontal projeto" } do |f| %>

  <% if @projeto.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@projeto.errors.count, "error") %> prohibited this projeto from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @projeto.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%#= f.text_field :user_id, :class => 'form-control' %>
      <%= f.collection_select :user_id, @users, :id ,:email, { include_blank: true }, { class: "form-control " } %>

    </div>
    <%=f.error_span(:user_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projetos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/projetos/edit.html.erb
<%- model_class = Projeto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projetos/index.html.erb
<%- model_class = Projeto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projetos.each do |projeto| %>
      <tr>
        <td><%= link_to projeto.id, projeto_path(projeto) %></td>
        <td><%= projeto.name %></td>
        <td><%= projeto.user_id %></td>
        <td><%=l projeto.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      projeto_path(projeto), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_projeto_path(projeto), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      projeto_path(projeto),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_projeto_path,
            :class => 'btn btn-primary' %>

app/views/projetos/new.html.erb
<%- model_class = Projeto -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projetos/show.html.erb
<%- model_class = Projeto -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @projeto.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @projeto.user.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              projetos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_projeto_path(@projeto), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              projeto_path(@projeto),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>